### ISSUE TITLE
JPA becoming reactive and Hibernate Session

### ISSUE THREAD

**Issue by afelguera** [PacktPublishing/Hands-On-Reactive-Programming-in-Spring-5#19]
Hi Tomasz,

I have a problem with Lazy relations in the Rx JPA Adapter. When using it, a LazyLoadingException arise because the session is no longer available when doing the getText() operations, such as in the following code:

	@Override
	public Flux<CountryDto> list() {
		return repository.findAll().map(e -> mapper.entityToDto(e, e.getText().orElse(new CountryText()))).log();
	}

Method signature in the interface is @Transactional.

Thank you very much in advance.

Best regards,
Toni Felguera

**Comment by OlegDokuka** [comment]
Hi @afelguera!

First of all, there is no Tomasz among the authors and maintainers. Please check if this is the right repo to ask the question.

Secondly, if you have any questions related to Hibernate / JPA - it is better to ask at the appropriate [repository](https://github.com/hibernate).
